# Numpy

Everything in Numpy revolves around the multidimensional array. To use it, first import the `numpy` package. It is customary to give it the name `np`.

In [139]:
import numpy as np

To create an array, use the `np.array` constructor. It understands list-of-lists type input, and as long as the input is well-formed, will do as expected.

In [140]:
np.array([])        # An empty array

array([], dtype=float64)

In [141]:
np.array(1.0)       # A scalar

array(1.)

In [142]:
np.array([1.0, 2.0, 3.0])   # A vector

array([1., 2., 3.])

In [143]:
np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])    # A matrix

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Every array has a **data type** and a **shape**.

The data type is the type of the objects stored in the array. Unlike regular Python lists, arrays are homogeneous, unable to store data of different types. For most of the time, Numpy is able to determine the data type itself, but you may give it pointers. For example,

In [144]:
a = np.array([1, 2])
a.dtype

dtype('int64')

In [145]:
a = np.array([1, 2], dtype=float)
a.dtype

dtype('float64')

In [146]:
np.array([0, 1], dtype=bool)

array([False,  True])

In [147]:
np.array([True, False], dtype=int)

array([1, 0])

The **shape** of an array is critically important. Most unexpected errors when working with Numpy occur from incorrect shapes.

The shape is a tuple, with one element for each dimension of the array, specifying the length of that dimension.

Therefore, the shape of a vector is a one-element tuple.

In [148]:
np.array([1, 2, 3, 4]).shape

(4,)

While the shape of a matrix is a two-element tuple.

In [149]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).shape

(3, 3)

**Exercise:** Check what the shape of a scalar is. What is the shape of an empty array?

## Array arithmetic and broadcasting

As a rule, Numpy arrays support standard Python mathematical operators like `+`, `*`, `/`, `//` and `**`. Without exception, and somewhat as a surprise to Matlab users, these operators are **ELEMENT-WISE**. That is to say, `a * b` is an array whose elements are the products of the elements of `a` and `b`, it is *not* a matrix-matrix product.

In [150]:
np.array([1, 2]) + np.array([3, 4])

array([4, 6])

In [151]:
np.array([[1, 2], [2, 2]]) * np.array([[1, 2], [3, 4]])

array([[1, 4],
       [6, 8]])

In [152]:
np.array([1, 2, 3]) ** 2

array([1, 4, 9])

The two arrays involved in an operation do not have to have the *same* shape, but the shapes have to be compatible according to a process known as "broadcasting", which is a classical example of something that is *difficult-at-first-but-easy-once-you-get-used-to-it*.™

There are two essential rules:

1. One array may have additional dimensions on the *left*, but not on the *right*.

   In other words, you may add a `(5,8)`-shape array to a `(2,4,5,8)`-shape array, and the result will be of shape `(2,4,5,8)` as expected. However, you may not add a `(2,4)`-shape array to that same `(2,4,5,8)`-shape array.
   
       Input 1:        5  8
                       |  |
       Input 2:  2  4  5  8
                 |  |  |  |
       Output:   2  4  5  8    => OK
       
       ----------------------------------
       
       Input 1:        2  4
                       |  |
       Input 2:  2  4  5  8
                 |  |  |  |
       Output:   2  4  ?  ?    => Not OK
       
2. Mismatching dimensions are okay, so long as one of them has length 1 (often called a "singleton" dimension).

       Input 1:        5  1
                       |  |
       Input 2:  2  4  5  8
                 |  |  |  |
       Output:   2  4  5  8    => OK
       
       ----------------------------------
       
       Input 1:        6  1
                       |  |
       Input 2:  2  4  1  8
                 |  |  |  |
       Output:   2  4  6  8    => OK
       
In both cases, the smaller array will have its data duplicated as necessary to ensure that everything matches up.

Adding a vector of size 2 to a matrix of size *N*×2 will then add the vector to each row of the matrix. For this reason I find it generally helpful to think of an *N*×2-matrix as a collection of *N* vectors of length 2, rather than as a collection of 2 vectors of length *N*. I recommend you use this rule of thumb when deciding what the shapes of your arrays should be, depending on what you want to store in them.

The two arrays involved in an operation do not have to have the *same* shape, but the shapes have to be compatible according to a process known as "broadcasting", which is a classical example of something that is *difficult-at-first-but-easy-once-you-get-used-to-it*.™

There are two essential rules:

1. One array may have additional dimensions on the *left*, but not on the *right*.

   In other words, you may add a `(5,8)`-shape array to a `(2,4,5,8)`-shape array, and the result will be of shape `(2,4,5,8)` as expected. However, you may not add a `(2,4)`-shape array to that same `(2,4,5,8)`-shape array.
   
       Input 1:        5  8
                       |  |
       Input 2:  2  4  5  8
                 |  |  |  |
       Output:   2  4  5  8    => OK
       
       ----------------------------------
       
       Input 1:        2  4
                       |  |
       Input 2:  2  4  5  8
                 |  |  |  |
       Output:   2  4  ?  ?    => Not OK
       
2. Mismatching dimensions are okay, so long as one of them has length 1 (often called a "singleton" dimension).

       Input 1:        5  1
                       |  |
       Input 2:  2  4  5  8
                 |  |  |  |
       Output:   2  4  5  8    => OK
       
       ----------------------------------
       
       Input 1:        6  1
                       |  |
       Input 2:  2  4  1  8
                 |  |  |  |
       Output:   2  4  6  8    => OK
       
In both cases, the smaller array will have its data duplicated as necessary to ensure that everything matches up.

Adding a vector of size 2 to a matrix of size *N*×2 will then add the vector to each row of the matrix. For this reason I find it generally helpful to think of an *N*×2-matrix as a collection of *N* vectors of length 2, rather than as a collection of 2 vectors of length *N*. I recommend you use this rule of thumb when deciding what the shapes of your arrays should be, depending on what you want to store in them.

## Matrix aritmethic

Since arithmetic with arrays is universally element-wise, you may reasonably ask how to do actual matrix multiplication in Numpy. This is possible with the `@` operator.

In [153]:
mx1 = np.array([[1.0, 3.0], [4.0, 2.0]])
mx2 = np.array([[-2.0, 5.0], [7.0, 3.0]])
mx1 @ mx2

array([[19., 14.],
       [ 6., 26.]])

The same operator will do matrix-vector multiplication if the right hand side is a vector.

In [154]:
vec = np.array([-1.0, -2.0])
mx1 @ vec

array([-7., -8.])

The `@`-operator also works with arrays of higher dimension, where this sort of thing is called "contraction," but it's really the same thing. The last dimension of the left-hand-side will be contracted with the first dimension on the right-hand-side.

This lets us do some cool things. For example, this is an inner product, $v^\intercal v$:

In [155]:
vec @ vec

5.0

And this is the often-seen generalized inner product $v^\intercal M v$:

In [156]:
vec @ mx1 @ vec

23.0

## Forming arrays

Forming large arrays is tedious with the list-of-lists style constructor. Fortunately, Numpy has a wide range of functions that can help us.

In [157]:
# An array full of ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [158]:
# An array full of zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [209]:
# An array full of garbage (if you try this, your garbage may be different)
np.empty((2,2), dtype=int)

array([[4611686018427387904, 4617315517961601024],
       [4619567317775286272, 4613937818241073152]])

In [160]:
# A diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [161]:
# A range, similar to Python's range() function
np.arange(5)

array([0, 1, 2, 3, 4])

In [162]:
np.arange(2, 5)

array([2, 3, 4])

In [163]:
np.arange(2, 5, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [164]:
# A vector of uniformly spaced points (start, end, number of points)
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [165]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

**WARNING:** `linspace` is almost universally preferable to `arange`. Due to floating point roundoff errors, `arange` may occasionally produce an array of a different size than you expect. `linspace` doesn't have that problem.

## Indexing arrays

You can access array elements by providing their index in a comma-separated fashion. Let's create a three-dimensional array to play around with.

In [166]:
myarray = np.array([[[1, 2, 3], [4, 5, 6]], 
                    [[7, 8, 9], [10, 11, 12]],
                    [[13, 14, 15], [16, 17, 18]],
                    [[19, 20, 21], [22, 23, 24]]])
myarray.shape

(4, 2, 3)

In [167]:
# Get a single element
myarray[1,1,2]

12

In [168]:
# Get a vector along the last dimension
myarray[1,1,:]

array([10, 11, 12])

In [169]:
# Get a vector along the middle dimension
myarray[1,:,2]

array([ 9, 12])

In [170]:
# Get a vector along the first dimension
myarray[:,1,2]

array([ 6, 12, 18, 24])

In [171]:
# Get a sub-matrix
myarray[2,:,:]

array([[13, 14, 15],
       [16, 17, 18]])

In [172]:
# The last example can also be written like this
myarray[2]

array([[13, 14, 15],
       [16, 17, 18]])

In [173]:
# ... or like this
myarray[2,...]

array([[13, 14, 15],
       [16, 17, 18]])

In [174]:
# Get another sub-matrix
myarray[:,:,2]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [175]:
# That example can also be written like this
myarray[...,2]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [176]:
# Like with lists, you can also do slicing
myarray[1:3,:,2]

array([[ 9, 12],
       [15, 18]])

You can grab multiple single elements at once by indexing with lists or tuples. For example:

In [177]:
myarray[(1,2), (0,1), (0,2)]

array([ 7, 18])

This is the same as doing

In [178]:
np.array([myarray[1,0,0], myarray[2,1,2]])

array([ 7, 18])

This is a frequent source of confusion, as people often expect this to create a 2×2×2 array, like this. (You don't have to double-check the indices. I got them right.)

In [179]:
np.array([[[myarray[1,0,0], myarray[1,0,2]],
           [myarray[1,1,0], myarray[1,1,2]]],
          [[myarray[2,0,0], myarray[2,0,2]],
           [myarray[2,1,0], myarray[2,1,2]]]])

array([[[ 7,  9],
        [10, 12]],

       [[13, 15],
        [16, 18]]])

To do this, you can use the `np.ix_` function, so named because of no conceivable reason whatsoever.

In [180]:
myarray[np.ix_((1,2), (0,1), (0,2))]

array([[[ 7,  9],
        [10, 12]],

       [[13, 15],
        [16, 18]]])

## Miscellaneous array manipulation

In what follows I will try to present a grab-bag of useful tricks when it comes to dealing with arrays. This list is colored by experience, essentially a "best of" of my Google search history of things I always need to look up to remember how it works. I hope that by creating this list, you will need to do less googling during this course.

In [181]:
# Number of dimensions of an array
myarray.ndim

3

In [182]:
# Number of elements of an array (product of the lengths of each dimension)
myarray.size

24

In [183]:
# Flattening an array to a vector
myarray.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [184]:
# Flat (single-dimensional) indexing
myarray.flat[3] 

4

In [185]:
# Vertical stacking (along the first dimension)
np.vstack([np.ones((3,2)), np.ones((2,2))]).shape

(5, 2)

In [186]:
# Horizontal stacking (along the second dimension)
np.hstack([np.ones((2,3)), np.ones((2,2))]).shape

(2, 5)

In [187]:
# Stacking along an arbitrary dimension, note that np.stack does something else!!!
np.concatenate([np.ones((1,2,3)), np.ones((1,2,5))], axis=2).shape

(1, 2, 8)

In [188]:
# Elementwise comparison
myarray == 1

array([[[ True, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])

In [189]:
# Use .any() or .all() to compress to a single boolean
(myarray == 1).any()

True

In [190]:
(myarray == 1).all()

False

In [191]:
(myarray > 0).all()

True

In [192]:
# Reshaping an array (you need to ensure that the total size is the same)
myarray.reshape((3,4,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [193]:
# Note that reshaping respects the same order as .flatten(), i.e. the following is true
(myarray.reshape((3,4,2)).flatten() == myarray.flatten()).all()

True

In [194]:
# Add new singleton dimensions to an array by using np.newaxis
myarray[:,np.newaxis,...].shape

(4, 1, 2, 3)

In [195]:
# This is common
_ = np.newaxis
myarray[:,_,...].shape

(4, 1, 2, 3)

In [196]:
# Sum along an axis
myarray.sum(0)

array([[40, 44, 48],
       [52, 56, 60]])

In [197]:
# Or along multiple axes
myarray.sum((0, 1))

array([ 92, 100, 108])

In [198]:
# Product also works
myarray.prod((0, 1))

array([ 24344320,  96342400, 264539520])

In [199]:
# Cumulative sums and products
myarray.cumsum(0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8, 10, 12],
        [14, 16, 18]],

       [[21, 24, 27],
        [30, 33, 36]],

       [[40, 44, 48],
        [52, 56, 60]]])

In [200]:
# Differencing
np.diff(np.arange(10)**2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [201]:
# Transposition generally inverts the order of the dimensions
myarray.T.shape

(3, 2, 4)

In [202]:
# More complex reordering can be done with .transpose(). For example, to swap the last two dimensions:
myarray.transpose((0,2,1)).shape

(4, 3, 2)

In [203]:
# np.squeeze removes singleton dimensions
test = myarray[:,_,_,:,_,:,_]
test.shape

(4, 1, 1, 2, 1, 3, 1)

In [204]:
np.squeeze(test).shape

(4, 2, 3)

In [205]:
# You can use np.where to filter an array, for example this returns a tuple of indexes where a condition holds.
np.where(myarray > 10)

(array([1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3]),
 array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]),
 array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [206]:
# That tuple can be used as an index itself, remember?
myarray[np.where(myarray > 10)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

Note that this trick in general will return a flat array, since there's no way of knowing whether the elements for which the condition is true will have a suitable multidimensional array-like structure. However, we can use `np.where` with three arguments to do this:

In [207]:
np.where(myarray > 10, myarray, -1)

array([[[-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
        [-1, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

The first argument is a condition. For the entries where the condition is true, elements are chosen from the second argument, otherwise the third. Like for general broadcasting, the shapes of the arguments must be compatible to make this work.

The best way to save arrays to disk is to use `np.save` and `np.load`.

In [208]:
np.save('filename.npy', myarray)
test = np.load('filename.npy')
(myarray == test).all()

True

The second best way to save arrays to disk is to use `np.savetxt` and `np.loadtxt`. As the name suggests, these files are readable by humans.